# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
- M3Core
- ModManager-Next

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'WinRelease'
  framework: 'netcoreapp3.1'

steps:
- checkout: self
  submodules: true 
  
- task: UseDotNet@2
  displayName: Install .NET 5.0 SDK
  inputs:
    packageType: 'sdk'
    version: '5.0.x' 

- task: UseDotNet@2
  displayName: Install .NET Core 3.1 SDK
  inputs:
    packageType: 'sdk'
    version: '3.1.x' 

- task: DotNetCoreCLI@2
  displayName: Build M3
  inputs:
    command: 'build'
    projects: 'MassEffectModManagerCore/MassEffectModManagerCore.csproj'
    arguments: '-c $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test M3
  inputs:
    command: 'test'
    projects: 'ME3TweaksModManager\\MassEffectModManagerCore.Tests\\MassEffectModManagerCore.Tests.csproj'
    arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Include=ME3TweaksModManager'

# Generate the report using ReportGenerator (https://github.com/danielpalme/ReportGenerator)
# First install the tool on the machine, then run it
- script: |
    dotnet tool install -g dotnet-reportgenerator-globaltool
    reportgenerator -reports:MassEffectModManagerCore.Tests/**/*.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:HtmlInline_AzurePipelines;Cobertura
  displayName: Create code coverage report

- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'
